/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.agriculture.ui;

/**
 *
 * @author SmartAgriculture
 */
public class DashboardForm extends javax.swing.JFrame {

    /**
     * Creates new form DashboardForm
     */
    public DashboardForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnFarmerManagement = new javax.swing.JButton();
        btnCropManagement = new javax.swing.JButton();
        btnSeasonManagement = new javax.swing.JButton();
        btnProductionEntry = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Smart Agriculture Management System");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(240, 248, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(34, 139, 34));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SMART AGRICULTURE MANAGEMENT SYSTEM");

        btnFarmerManagement.setBackground(new java.awt.Color(46, 139, 87));
        btnFarmerManagement.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFarmerManagement.setForeground(new java.awt.Color(255, 255, 255));
        btnFarmerManagement.setText("Farmer Management");
        btnFarmerManagement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFarmerManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFarmerManagementActionPerformed(evt);
            }
        });

        btnCropManagement.setBackground(new java.awt.Color(60, 179, 113));
        btnCropManagement.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCropManagement.setForeground(new java.awt.Color(255, 255, 255));
        btnCropManagement.setText("Crop Management");
        btnCropManagement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCropManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCropManagementActionPerformed(evt);
            }
        });

        btnSeasonManagement.setBackground(new java.awt.Color(0, 128, 128));
        btnSeasonManagement.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSeasonManagement.setForeground(new java.awt.Color(255, 255, 255));
        btnSeasonManagement.setText("Season Management");
        btnSeasonManagement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSeasonManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeasonManagementActionPerformed(evt);
            }
        });

        btnProductionEntry.setBackground(new java.awt.Color(70, 130, 180));
        btnProductionEntry.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnProductionEntry.setForeground(new java.awt.Color(255, 255, 255));
        btnProductionEntry.setText("Production Entry");
        btnProductionEntry.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProductionEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductionEntryActionPerformed(evt);
            }
        });

        btnReports.setBackground(new java.awt.Color(255, 140, 0));
        btnReports.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReports.setForeground(new java.awt.Color(255, 255, 255));
        btnReports.setText("Generate Reports");
        btnReports.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(178, 34, 34));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(btnFarmerManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCropManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeasonManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProductionEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReports, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(btnFarmerManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnCropManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnSeasonManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnProductionEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnReports, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFarmerManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFarmerManagementActionPerformed
        new FarmerForm().setVisible(true);
    }//GEN-LAST:event_btnFarmerManagementActionPerformed

    private void btnCropManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCropManagementActionPerformed
        new CropForm().setVisible(true);
    }//GEN-LAST:event_btnCropManagementActionPerformed

    private void btnSeasonManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeasonManagementActionPerformed
        new SeasonForm().setVisible(true);
    }//GEN-LAST:event_btnSeasonManagementActionPerformed

    private void btnProductionEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductionEntryActionPerformed
        new ProductionForm().setVisible(true);
    }//GEN-LAST:event_btnProductionEntryActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        new ReportForm().setVisible(true);
    }//GEN-LAST:event_btnReportsActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to exit?", "Confirm Exit", 
            javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCropManagement;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFarmerManagement;
    private javax.swing.JButton btnProductionEntry;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnSeasonManagement;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
